import type { ReferralRecord } from "@/lib/types";

export const REFERRALS: ReferralRecord[] = [
  {
    id: "ref1",
    referrerEventId: "ev6",
    referrerName: "مریم اسدی",
    refereeName: "شیدا و کاوه رحیمی",
    refereePhone: "۰۹۱۲۷۷۸۸۹۹۰",
    dateReferred: "۱۰ اردیبهشت ۱۴۰۵",
    status: "تبدیل به مشتری",
    convertedEventId: "ev4",
    rewardType: "تخفیف نقدی",
    rewardValue: "۵۰٬۰۰۰٬۰۰۰ تومان",
    rewardStatus: "پرداخت‌شده",
    notes: "مریم بعد از مراسم خودش، شیدا رو معرفی کرد.",
  },
  {
    id: "ref2",
    referrerEventId: "ev-me",
    referrerName: "آیدا و آرمین",
    refereeName: "ترانه محسنی",
    refereePhone: "۰۹۱۹۵۵۶۶۷۷۸",
    dateReferred: "۲ خرداد ۱۴۰۵",
    status: "در حال بررسی",
    rewardType: "خدمات رایگان",
    rewardValue: "یک جلسه عکاسی اضافه",
    rewardStatus: "بدون پاداش",
    notes: "منتظر تصمیم نهایی ترانه بین دو باغ هستیم.",
  },
  {
    id: "ref3",
    referrerEventId: "ev2",
    referrerName: "نیلوفر و کیان صفری",
    refereeName: "پریسا و امیر کاظمی",
    refereePhone: "۰۹۳۵۴۴۵۶۶۷۸",
    dateReferred: "۲۵ فروردین ۱۴۰۵",
    status: "تبدیل به مشتری",
    convertedEventId: "ev4",
    rewardType: "هدیه",
    rewardValue: "ست کریستال یلان",
    rewardStatus: "پرداخت‌نشده",
  },
  {
    id: "ref4",
    referrerEventId: "ev3",
    referrerName: "ترانه و کیان محسنی",
    refereeName: "هستی رادمنش",
    refereePhone: "۰۹۳۶۴۴۵۵۶۶۷",
    dateReferred: "۵ اسفند ۱۴۰۴",
    status: "رد شده",
    rewardType: "تخفیف نقدی",
    rewardValue: "—",
    rewardStatus: "بدون پاداش",
    notes: "هستی به دلیل بودجه، مراسم را جای دیگری برگزار کرد.",
  },
  {
    id: "ref5",
    referrerEventId: "ev5",
    referrerName: "الناز طاهری",
    refereeName: "نگین صادقی",
    refereePhone: "۰۹۱۲۱۲۳۴۵۶۷",
    dateReferred: "۱۸ اردیبهشت ۱۴۰۵",
    status: "لید جدید",
    rewardType: "تخفیف نقدی",
    rewardValue: "۳۰٬۰۰۰٬۰۰۰ تومان",
    rewardStatus: "بدون پاداش",
  },
];
